# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"

  lane :beta do
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    increment_version_number
    app_store_connect_api_key(
      key_id: "R7C58W4QUT",
      issuer_id: "cb6db6d4-81e6-4748-abd4-f8b4b56bc75d",
      key_filepath: "~/keystore/AuthKey_R7C58W4QUT.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    build_app(workspace: "goodtags.xcworkspace", scheme: "goodtags")
  
    upload_to_testflight
  end

  lane :release do
    increment_build_number(xcodeproj: "goodtags.xcodeproj")
    build_app(workspace: "goodtags.xcworkspace", scheme: "goodtags")
    upload_to_app_store(skip_metadata: true, skip_screenshots: false)
  end
end
